[package]
name = "relay_rpc"
version = "0.1.0"
edition = "2021"

[features]
cacao = ["dep:k256", "dep:sha3"]

[dependencies]
bs58 = "0.4"
data-encoding = "2.3"
derive_more = { version = "0.99", default-features = false, features = ["display", "from", "as_ref", "as_mut"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde-aux = { version = "4.1", default-features = false }
serde_json = "1.0"
thiserror = "1.0"
ed25519-dalek = { git = "https://github.com/dalek-cryptography/ed25519-dalek.git", rev = "7529d65" }
rand = "0.7"
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
regex = "1.7"
once_cell = "1.16"
jsonwebtoken = "9.3.0"
k256 = { version = "0.13", optional = true }
sha3 = { version = "0.10", optional = true }
